PyPowerDNS/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
PyPowerDNS/api.py,sha256=ayuPzzCdPtxrQ60TZ8vbKBh8Q_SqZXTRqP_4csK0Im4,8730
PyPowerDNS/exceptions.py,sha256=rWPWpnOfFaZ7-2Bjir91b94SwnLoLDfft2eTFW2qMJ4,411
PyPowerDNS/objects.py,sha256=fL3KGiOJlIY8JS6Npa4fe9pVjx-lSquT7PUrNzuzSjs,4508
PyPowerDNS-2020.5.2.dist-info/LICENSE,sha256=o-MOeR1ubHEdYt1VtnuVgEkvPELmtVghhH_jcpyOD_k,1072
PyPowerDNS-2020.5.2.dist-info/METADATA,sha256=y7F9wUknX8MhSAx5noLQwI4w0jrBIu2S39BqxRULaFI,1256
PyPowerDNS-2020.5.2.dist-info/WHEEL,sha256=g4nMs7d-Xl9-xC9XovUrsDHGXt-FT0E17Yqo92DEfvY,92
PyPowerDNS-2020.5.2.dist-info/top_level.txt,sha256=WfWlEFbu5uoB3-H8b99NmqxfSD5eDw-6ivtItplm2PU,11
PyPowerDNS-2020.5.2.dist-info/RECORD,,
