PyPowerDNS/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
PyPowerDNS/api.py,sha256=rrHbM1qMY-6qq_XDtpijScpX4jJKkJcm-77wkmWR1nk,8708
PyPowerDNS/exceptions.py,sha256=rWPWpnOfFaZ7-2Bjir91b94SwnLoLDfft2eTFW2qMJ4,411
PyPowerDNS/objects.py,sha256=xu0qx_TZ9h7l2FccTxCawhe_RzwJ_DMrMcawdZGj88E,4507
PyPowerDNS-2020.5.1.dist-info/LICENSE,sha256=o-MOeR1ubHEdYt1VtnuVgEkvPELmtVghhH_jcpyOD_k,1072
PyPowerDNS-2020.5.1.dist-info/METADATA,sha256=8eZQUCbmhxnvlTJWmq27PhuypYuPcQOhS4GwFdnWXZc,1256
PyPowerDNS-2020.5.1.dist-info/WHEEL,sha256=g4nMs7d-Xl9-xC9XovUrsDHGXt-FT0E17Yqo92DEfvY,92
PyPowerDNS-2020.5.1.dist-info/top_level.txt,sha256=WfWlEFbu5uoB3-H8b99NmqxfSD5eDw-6ivtItplm2PU,11
PyPowerDNS-2020.5.1.dist-info/RECORD,,
